/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package irrgarten.UI;

/**
 *
 * @author paula
 */
public class Button2 extends javax.swing.JDialog {

    private boolean conservar;
    /**
     * Creates new form Button2
     */
    public Button2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siConservarTurno = new javax.swing.JButton();
        noConservarTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        siConservarTurno.setText("Conservar turno");
        siConservarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siConservarTurnoActionPerformed(evt);
            }
        });

        noConservarTurno.setText("No conservar turno");
        noConservarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noConservarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(siConservarTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(noConservarTurno)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siConservarTurno)
                    .addComponent(noConservarTurno))
                .addGap(137, 137, 137))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siConservarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siConservarTurnoActionPerformed
        conservar=true;
        dispose();
    }//GEN-LAST:event_siConservarTurnoActionPerformed

    private void noConservarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noConservarTurnoActionPerformed
        conservar=false;
        dispose();
    }//GEN-LAST:event_noConservarTurnoActionPerformed

    public boolean getConservar() {
    
        setVisible(true);
        return conservar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton noConservarTurno;
    private javax.swing.JButton siConservarTurno;
    // End of variables declaration//GEN-END:variables
}
