/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package irrgarten.UI;

import javax.swing.JButton;
import irrgarten.GameState;
import irrgarten.Game;
/**
 *
 * @author paula
 */
public class Button extends javax.swing.JDialog {

    private boolean siguiente;
    /**
     * Creates new form Button
     */
    public Button(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siPasarTurno = new javax.swing.JButton();
        noPasarTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        siPasarTurno.setText("Pasar turno");
        siPasarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siPasarTurnoActionPerformed(evt);
            }
        });

        noPasarTurno.setText("No pasar turno");
        noPasarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPasarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(siPasarTurno)
                .addGap(44, 44, 44)
                .addComponent(noPasarTurno)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siPasarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noPasarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siPasarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siPasarTurnoActionPerformed
        siguiente=true;
        dispose();
    }//GEN-LAST:event_siPasarTurnoActionPerformed

    private void noPasarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPasarTurnoActionPerformed
        siguiente=false;
        dispose();
    }//GEN-LAST:event_noPasarTurnoActionPerformed
    
    public boolean getPasar() {
    
        setVisible(true);
        return siguiente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton noPasarTurno;
    private javax.swing.JButton siPasarTurno;
    // End of variables declaration//GEN-END:variables
}
